### ISSUE TITLE
Tweak color contrast of highlighting

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#393]
Once https://github.com/tabatkins/highlighter/issues/25 is resolved we should update our copy of these styles in `resources.whatwg.org/standard-shared-with-dev.css`.

(See #392 for context.)

**Comment by hidde** [comment]
It took us a a couple of years, but this has just been resolved in https://github.com/tabatkins/highlighter/pull/26. 

Thanks past-Anne for documenting what to update :-)

**Comment by annevk** [comment]
@hidde could you review #491?

I think we might still have issues for dark mode. I did not attempt to tackle that.
